# Generated by Django 5.0.6 on 2024-06-23 16:05

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('account', '0002_user_age_user_dob_user_location'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='user',
            name='location',
        ),
    ]
