# Generated by Django 5.0.6 on 2024-07-02 17:18

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('account', '0003_remove_user_images_remove_user_video_profileimage'),
    ]

    operations = [
        migrations.AddField(
            model_name='user',
            name='images',
            field=models.FileField(blank=True, null=True, upload_to='upload/'),
        ),
        migrations.DeleteModel(
            name='ProfileImage',
        ),
    ]
