# Generated by Django 5.0.6 on 2024-06-23 16:16

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('account', '0004_user_city'),
    ]

    operations = [
        migrations.AddField(
            model_name='user',
            name='intrest',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
        migrations.AddField(
            model_name='user',
            name='nationality',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
    ]
