# Generated by Django 5.0.6 on 2024-06-23 17:03

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('account', '0006_user_gender'),
    ]

    operations = [
        migrations.AddField(
            model_name='user',
            name='height',
            field=models.PositiveIntegerField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='user',
            name='rel_status',
            field=models.CharField(choices=[('S', 'Single'), ('SK', 'Single with Kid(s)'), ('D', 'Divorced'), ('DK', 'Divorced with Kid(s)'), ('W', 'Widowed'), ('WK', 'Widowed with Kid(s)'), ('SP', 'Separated'), ('SPK', 'Separated with Kid(s)')], default='S', max_length=3),
        ),
    ]
