# Generated by Django 5.0.6 on 2024-06-23 17:18

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('account', '0008_user_community_user_drinking_user_fath_user_images_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='user',
            name='intrest',
        ),
    ]
