# Generated by Django 5.0.6 on 2024-06-23 17:19

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('account', '0009_remove_user_intrest'),
    ]

    operations = [
        migrations.AddField(
            model_name='user',
            name='intrest',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
    ]
