# Generated by Django 5.0.6 on 2024-07-24 05:02

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('account', '0010_remove_user_community_remove_user_fath_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='user',
            name='location',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
        migrations.AlterField(
            model_name='user',
            name='drinking',
            field=models.CharField(choices=[('Regular', 'Regular'), ('Socialy', 'Socialy'), ('Occasionally', 'Occasionally'), ('Teetotaler', 'Teetotaler'), ('Plan to Quit', 'Plan to Quit')], default='Teetotaler', max_length=15),
        ),
        migrations.AlterField(
            model_name='user',
            name='gender',
            field=models.CharField(choices=[('Male', 'Male'), ('Female', 'Female'), ('Other', 'Other')], default='Male', max_length=10),
        ),
        migrations.AlterField(
            model_name='user',
            name='rel_status',
            field=models.CharField(choices=[('Single', 'Single'), ('Single with Kid(s)', 'Single with Kid(s)'), ('Divorced', 'Divorced'), ('Divorced with Kid(s)', 'Divorced with Kid(s)'), ('Widowed', 'Widowed'), ('Widowed with Kid(s)', 'Widowed with Kid(s)'), ('Separated', 'Separated'), ('Separated with Kid(s)', 'Separated with Kid(s)')], default='Single', max_length=25),
        ),
        migrations.AlterField(
            model_name='user',
            name='smoke',
            field=models.CharField(choices=[('No', 'No'), ('Yes', 'Yes'), ('Plan to Quit', 'Plan to Quit')], default='No', max_length=15),
        ),
    ]
