# Generated by Django 5.0.6 on 2024-07-25 05:22

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Dating', '0002_alter_genderselect_genderselect_friendconnection_and_more'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='message',
            options={'ordering': ['timestamp']},
        ),
        migrations.RenameField(
            model_name='message',
            old_name='is_read',
            new_name='reported',
        ),
        migrations.AddField(
            model_name='friendconnection',
            name='not_interest',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='friendconnection',
            name='short_list',
            field=models.BooleanField(default=False),
        ),
    ]
